# Generated by Django 2.0.6 on 2018-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('previewText', models.TextField()),
            ],
        ),
    ]
